// <auto-generated />
using System;
using GiaPha_Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiaPha_Infrastructure.Migrations
{
    [DbContext(typeof(DbGiaPha))]
    [Migration("20260204073911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GiaPha_Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ChiHo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("HoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TenChiHo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("TruongChiId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("HoId");

                    b.HasIndex("TruongChiId");

                    b.ToTable("ChiHos", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Doi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("HoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SoDoi")
                        .HasColumnType("int");

                    b.Property<string>("TenDoi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HoId");

                    b.ToTable("Dois", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Ho", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TenHo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("ThuyToId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ThuyToId");

                    b.ToTable("Hos", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.HonNhan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChongId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("NgayKetHon")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiKetHon")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("VoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChongId");

                    b.HasIndex("VoId");

                    b.ToTable("HonNhans", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.MoPhan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("KinhDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("ThanhVienId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ViDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("MoPhans", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChiHoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("HoId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("NguoiNhanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ChiHoId");

                    b.HasIndex("DaDoc");

                    b.HasIndex("HoId");

                    b.HasIndex("NguoiNhanId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.QuanHeChaCon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChaMeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConId")
                        .HasColumnType("char(36)");

                    b.Property<int>("LoaiQuanHe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChaMeId");

                    b.HasIndex("ConId");

                    b.ToTable("QuanHeChacons", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.SuKien", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LoaiSuKien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("NgayXayRa")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ThanhVienId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("SuKiens", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.TaiKhoanNguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActivationCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("User");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ThanhVienId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.HasIndex("ThanhVienId");

                    b.ToTable("TaiKhoanNguoiDungs", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.TepTin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("ThanhVienId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("TepTins", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ThanhTuu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("NamDatDuoc")
                        .HasColumnType("int");

                    b.Property<string>("TenThanhTuu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("ThanhVienId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("ThanhTuus", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ThanhVien", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChiHoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DoiId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("HoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayMat")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiSinh")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TieuSu")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ChiHoId");

                    b.HasIndex("DoiId");

                    b.HasIndex("HoId");

                    b.ToTable("ThanhViens", (string)null);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ChiHo", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.Ho", "Ho")
                        .WithMany("ChiHos")
                        .HasForeignKey("HoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "TruongChi")
                        .WithMany()
                        .HasForeignKey("TruongChiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ho");

                    b.Navigation("TruongChi");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Doi", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.Ho", "Ho")
                        .WithMany("Dois")
                        .HasForeignKey("HoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ho");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Ho", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "ThuyTo")
                        .WithMany()
                        .HasForeignKey("ThuyToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ThuyTo");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.HonNhan", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "Chong")
                        .WithMany()
                        .HasForeignKey("ChongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "Vo")
                        .WithMany()
                        .HasForeignKey("VoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chong");

                    b.Navigation("Vo");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.MoPhan", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("ThanhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Notification", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ChiHo", "ChiHo")
                        .WithMany()
                        .HasForeignKey("ChiHoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GiaPha_Domain.Entities.Ho", "Ho")
                        .WithMany()
                        .HasForeignKey("HoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ChiHo");

                    b.Navigation("Ho");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.QuanHeChaCon", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "ChaMe")
                        .WithMany()
                        .HasForeignKey("ChaMeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "Con")
                        .WithMany()
                        .HasForeignKey("ConId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChaMe");

                    b.Navigation("Con");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.SuKien", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("ThanhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.TaiKhoanNguoiDung", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("ThanhVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.TepTin", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("ThanhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ThanhTuu", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("ThanhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ThanhVien", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ChiHo", "ChiHo")
                        .WithMany("ThanhViens")
                        .HasForeignKey("ChiHoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiaPha_Domain.Entities.Doi", "Doi")
                        .WithMany()
                        .HasForeignKey("DoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiaPha_Domain.Entities.Ho", "Ho")
                        .WithMany()
                        .HasForeignKey("HoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiHo");

                    b.Navigation("Doi");

                    b.Navigation("Ho");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ChiHo", b =>
                {
                    b.Navigation("ThanhViens");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Ho", b =>
                {
                    b.Navigation("ChiHos");

                    b.Navigation("Dois");
                });
#pragma warning restore 612, 618
        }
    }
}
